#!/usr/bin/env bash

set -x
set -eo pipefail

echo "[+] Running $0 with pid: $$"

type stow 1>/dev/null 2>&1 || { echo "GNU Stow is required" >&2; exit 1; }

# Stow current directory into $HOME
stow -t "$HOME" .


